[window]
opacity = 0.85  # Background transparency (0.0 to 1.0)
decorations = "none"

[window.padding]
x = 12
y = 12

[font]
size = 11.0

[font.normal]
family = "MesloLGS Nerd Font"
style = "Regular"

